# Generated by Django 6.0.1 on 2026-02-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_game_imageurl_answer_answer_image_game_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
    ]
