# Generated by Django 6.0.1 on 2026-02-11 15:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answer_sound'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_tts',
            field=models.FileField(blank=True, null=True, upload_to=core.models.answer_tts_path),
        ),
        migrations.AddField(
            model_name='game',
            name='titulo_tts',
            field=models.FileField(blank=True, null=True, upload_to=core.models.game_tts_path),
        ),
        migrations.AddField(
            model_name='question',
            name='indication_tts',
            field=models.FileField(blank=True, null=True, upload_to=core.models.question_indication_tts_path),
        ),
        migrations.AddField(
            model_name='question',
            name='title_tts',
            field=models.FileField(blank=True, null=True, upload_to=core.models.question_title_tts_path),
        ),
    ]
